version: 0.2
phases:
  build:
    commands:
      - ls -la
      - printenv
      - cp -r $CODEBUILD_SRC_DIR_SourceArtifact2/. $CODEBUILD_SRC_DIR
      - ls -la
      - pwd
artifacts:
  files:
    - ‘**/*’
  base-directory: $CODEBUILD_SRC_DIR
