version: 0.2
phases:
  build:
    commands:
      - ls -la
      - codebuild-breakpoint
      - cp -r $CODEBUILD_SRC_DIR_SourceArtifact2/. $$CODEBUILD_SRC_DIR_SourceArtifact
      - ls -la
artifacts:
  files:
    - ‘**.*’
